blank_issues_enabled: false
contact_links:
  - name: Questions and support
    url: 'https://github.com/ycm-core/YouCompleteMe/tree/master?tab=readme-ov-file#help-advice-support'
    about: Please ask and answer questions here.
